### Sign up user
POST http://localhost:5000/api/auth/sign-up
Content-Type: application/json

{
    "full_name": "John Doe",
    "email": "john.doe@example.com",
    "password": "password"
}


### Sign in user
POST http://localhost:5000/api/auth/sign-in
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "password"
}

### Refresh token
POST http://localhost:5000/api/auth/refresh-token

### Sign out user
POST http://localhost:5000/api/auth/sign-out